### ISSUE TITLE
integration error?

### ISSUE THREAD

**Issue by zarigata** [rawandahmad698/Dalle-Discord#18]
![image](https://user-images.githubusercontent.com/39637452/198903252-48c4cbdf-1e45-40a4-81f6-34b488ed43d0.png)
maybe i did somethjing wrong?

**Comment by zarigata** [comment]
dalle-discord-dalle-discord-1 | Traceback (most recent call last):
dalle-discord-dalle-discord-1 |   File "/app/bot.py", line 222, in <module>
dalle-discord-dalle-discord-1 |     asyncio.run(main())
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
dalle-discord-dalle-discord-1 |     return loop.run_until_complete(main)
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
dalle-discord-dalle-discord-1 |     return future.result()
dalle-discord-dalle-discord-1 |   File "/app/bot.py", line 220, in main
dalle-discord-dalle-discord-1 |     await bot.start(c['discord_token'])
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 746, in start
dalle-discord-dalle-discord-1 |     await self.connect(reconnect=reconnect)
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 672, in connect
dalle-discord-dalle-discord-1 |     raise PrivilegedIntentsRequired(exc.shard_id) from None
dalle-discord-dalle-discord-1 | discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
dalle-discord-dalle-discord-1 | Traceback (most recent call last):
dalle-discord-dalle-discord-1 |   File "/app/bot.py", line 222, in <module>
dalle-discord-dalle-discord-1 |     asyncio.run(main())
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
dalle-discord-dalle-discord-1 |     return loop.run_until_complete(main)
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
dalle-discord-dalle-discord-1 |     return future.result()
dalle-discord-dalle-discord-1 |   File "/app/bot.py", line 220, in main
dalle-discord-dalle-discord-1 |     await bot.start(c['discord_token'])
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 746, in start
dalle-discord-dalle-discord-1 |     await self.connect(reconnect=reconnect)
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 672, in connect
dalle-discord-dalle-discord-1 |     raise PrivilegedIntentsRequired(exc.shard_id) from None
dalle-discord-dalle-discord-1 | discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
dalle-discord-dalle-discord-1 | Traceback (most recent call last):
dalle-discord-dalle-discord-1 |   File "/app/bot.py", line 222, in <module>
dalle-discord-dalle-discord-1 |     asyncio.run(main())
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
dalle-discord-dalle-discord-1 |     return loop.run_until_complete(main)
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
dalle-discord-dalle-discord-1 |     return future.result()
dalle-discord-dalle-discord-1 |   File "/app/bot.py", line 220, in main
dalle-discord-dalle-discord-1 |     await bot.start(c['discord_token'])
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 746, in start
dalle-discord-dalle-discord-1 |     await self.connect(reconnect=reconnect)
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 672, in connect
dalle-discord-dalle-discord-1 |     raise PrivilegedIntentsRequired(exc.shard_id) from None
dalle-discord-dalle-discord-1 | discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
dalle-discord-dalle-discord-1 | Traceback (most recent call last):
dalle-discord-dalle-discord-1 |   File "/app/bot.py", line 222, in <module>
dalle-discord-dalle-discord-1 |     asyncio.run(main())
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
dalle-discord-dalle-discord-1 |     return loop.run_until_complete(main)
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
dalle-discord-dalle-discord-1 |     return future.result()
dalle-discord-dalle-discord-1 |   File "/app/bot.py", line 220, in main
dalle-discord-dalle-discord-1 |     await bot.start(c['discord_token'])
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 746, in start
dalle-discord-dalle-discord-1 |     await self.connect(reconnect=reconnect)
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 672, in connect
dalle-discord-dalle-discord-1 |     raise PrivilegedIntentsRequired(exc.shard_id) from None
dalle-discord-dalle-discord-1 | discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.
dalle-discord-dalle-discord-1 | Traceback (most recent call last):
dalle-discord-dalle-discord-1 |   File "/app/bot.py", line 222, in <module>
dalle-discord-dalle-discord-1 |     asyncio.run(main())
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
dalle-discord-dalle-discord-1 |     return loop.run_until_complete(main)
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
dalle-discord-dalle-discord-1 |     return future.result()
dalle-discord-dalle-discord-1 |   File "/app/bot.py", line 220, in main
dalle-discord-dalle-discord-1 |     await bot.start(c['discord_token'])
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 746, in start
dalle-discord-dalle-discord-1 |     await self.connect(reconnect=reconnect)
dalle-discord-dalle-discord-1 |   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 672, in connect
dalle-discord-dalle-discord-1 |     raise PrivilegedIntentsRequired(exc.shard_id) from None
dalle-discord-dalle-discord-1 | discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead.

**Comment by zarigata** [comment]
oauth was enabled... sorry
