### ISSUE TITLE
Says its running but bot isn't online nor working

### ISSUE THREAD

**Issue by Wolliger** [rawandahmad698/Dalle-Discord#19]
<img width="713" alt="image" src="https://user-images.githubusercontent.com/48773505/201522619-20b3fe85-f23e-4cac-b5c4-74d6a590fcbb.png">

**Comment by Wolliger** [comment]
<img width="376" alt="image" src="https://user-images.githubusercontent.com/48773505/201522641-01b6975c-8a45-4d5f-ba3e-11f57e1e6112.png">

**Comment by Wolliger** [comment]
"2022-11-13 13:57:25 Traceback (most recent call last):
2022-11-13 13:57:25   File "/app/bot.py", line 222, in <module>
2022-11-13 13:57:25     asyncio.run(main())
2022-11-13 13:57:25   File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
2022-11-13 13:57:25     return loop.run_until_complete(main)
2022-11-13 13:57:25   File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
2022-11-13 13:57:25     return future.result()
2022-11-13 13:57:25   File "/app/bot.py", line 220, in main
2022-11-13 13:57:25     await bot.start(c['discord_token'])
2022-11-13 13:57:25   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 746, in start
2022-11-13 13:57:25     await self.connect(reconnect=reconnect)
2022-11-13 13:57:25   File "/usr/local/lib/python3.10/site-packages/discord/client.py", line 672, in connect
2022-11-13 13:57:25     raise PrivilegedIntentsRequired(exc.shard_id) from None
2022-11-13 13:57:25 discord.errors.PrivilegedIntentsRequired: Shard ID None is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead."

**Comment by rawandahmad698** [comment]
"is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead."

Enable Privileged Intents in your bot settings in Discord

**Comment by Anon0511** [comment]
> "is requesting privileged intents that have not been explicitly enabled in the developer portal. It is recommended to go to https://discord.com/developers/applications/ and explicitly enable the privileged intents within your application's page. If this is not possible, then consider disabling the privileged intents instead."
> 
> Enable Privileged Intents in your bot settings in Discord

I do have the same issue. I have enabled all Privileged Intents and not a single line of anything is in the container logs. The container is running but no bot on the discord server.
I have created a new application with a new Bot Token for it and changed the Webhook URL in data.yaml.
Manually executing into the container and running `python bot.py` results in:
```
Made with ❤️ by Rawand Ahmed Shaswar in Kurdistan
Bot is online! Send requests with:
 ! dalle <query>
```
