### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by Xechorizo** [rawandahmad698/Dalle-Discord#2]
Running into the following:

```
[-] MyDiscord#1234 called !dalle robocop returns to monke
Ignoring exception in command dalle:
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\aiohttp\connector.py", line 969, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore  # noqa
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1089, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1119, in _create_connection_transport
    await waiter
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 534, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\asyncio\sslproto.py", line 188, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\ssl.py", line 975, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:997)```

**Comment by Xechorizo** [comment]
Workaround (**_NOT RECOMMENDED_**):

Dalle.py
Line 11: `from aiohttp import TCPConnector`
Line 78: `async with aiohttp.ClientSession(connector=TCPConnector(ssl=False)) as session:`

**Comment by rawandahmad698** [comment]
This happens on some windows devices. Thanks for the fix, you could also use `ssl=false` directly on the `client`, without any imports

**Comment by comicsansgreenki** [comment]
Sounds like you're missing an SSL cert, you haven't updated them, or the Dall-E Mini servers were still running expired certs.
Is this still happening on your end?

**Comment by Xechorizo** [comment]
Unknown if still occurring
